labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Controllers/OsobaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCREST.Service.Models;
using System.Net;
using System.Text;
using System.Web.Script.Serialization;
using System.Collections.Specialized;

namespace MVCREST.Server.Controllers
{    
    public class OsobaController : Controller
    {
        //izmijeniti ovisno o portu na kojem se servis pokrece!!!
        private string domenaServisa = "http://localhost:38550";

        //prikaz svih osoba
        public ActionResult Index()
        {
            WebClient webClient = new WebClient();
            webClient.Headers["User-Agent"] = Request.UserAgent;
            string responseData = Encoding.UTF8.GetString(
                webClient.DownloadData(domenaServisa + "/api/Osobe/Index"));
            JavaScriptSerializer deserializer=new JavaScriptSerializer();
            JSONOdgovorOsobe odgovor = deserializer.Deserialize<JSONOdgovorOsobe>(responseData);

            return View(odgovor);
        }

        //prikaz određene osobe
        public ActionResult Prikazi(long? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            WebClient webClient = new WebClient();
            webClient.Headers["User-Agent"] = Request.UserAgent;
            string responseData = Encoding.UTF8.GetString(
                webClient.DownloadData(domenaServisa + "/api/Osobe/Index/" + id));
            JavaScriptSerializer deserializer = new JavaScriptSerializer();
            JSONOdgovorOsoba odgovor = deserializer.Deserialize<JSONOdgovorOsoba>(responseData);

            return View(odgovor);
        }

        //prikazi dodavanje osobe
        public ActionResult Dodaj()
        {
            return View();
        }

        //izvrsi dodavanje osobe
        [HttpPost]
        public ActionResult Dodaj(ViewModelOsoba model)
        {
            NameValueCollection postData = new NameValueCollection();
            postData["ime"] = model.Ime;
            postData["prezime"] = model.Prezime;

            WebClient webClient = new WebClient();
            webClient.Headers["User-Agent"] = Request.UserAgent;            
            string responseData = Encoding.UTF8.GetString(
                webClient.UploadValues(domenaServisa + "/api/Osobe/Index", "POST", postData));
            JavaScriptSerializer deserializer = new JavaScriptSerializer();
            Odgovor odgovor = deserializer.Deserialize<Odgovor>(responseData);

            if (odgovor.Tip == Odgovor.GRESKA)
            {
                ModelState.AddModelError(odgovor.Kljuc, odgovor.Text);
                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }            
        }
    }
}

labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Views/Osoba/Dodaj.cshtml
@model ViewModelOsoba
@using MVCREST.Service.Models
@{
    ViewBag.Title = "Unos osobe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Greška tijekom unosa osobe. Popravite pogreške i pokušajte ponovo.")
    <div>
        <fieldset>
            <legend>Unos osobe</legend>

            <div class="editor-label">
                Ime
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Ime)
                @Html.ValidationMessageFor(m => m.Ime)
            </div>

            <div class="editor-label">
                Prezime
            </div>
            <div class="editor-field">
                @Html.PasswordFor(m => m.Prezime)
                @Html.ValidationMessageFor(m => m.Prezime)
            </div>
            
            <p>
                <input type="submit" value="Dodaj osobu" />
            </p>
        </fieldset>
    </div>
}

labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Views/Osoba/Index.cshtml
@model JSONOdgovorOsobe
@using MVCREST.Service.Models
@using MVCREST.BaseModel;
@{
    ViewBag.Title = "Lista osoba";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
<legend>Osobe</legend>
@if (Model.Osobe.Count == 0)
{
    <div class="editor-label">
        Nema osoba za dohvat!
    </div>
}
else
{
    foreach (Osoba o in Model.Osobe)
    {
        <fieldset>
            <legend>@o.Ime @o.Prezime (ID:@o.Id)</legend>

            <div class="editor-label">
                Id: <font style="font-weight:bold">@o.Id</font>
            </div>

            <div class="editor-label">
                Ime: <font style="font-weight:bold">@o.Ime</font>
            </div>

            <div class="editor-label">
                Prezime: <font style="font-weight:bold">@o.Prezime</font>
            </div>

            <div class="editor-label">
                <a title="Prikaži detalje" href="@Url.RouteUrl("PrikaziOsobu", new { id = o.Id })">Prikaži detalje</a>
            </div>
        </fieldset>
    }
}
</fieldset>

labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Views/Osoba/Prikazi.cshtml
@model JSONOdgovorOsoba
@using MVCREST.Service.Models
@using MVCREST.BaseModel;
@{
    ViewBag.Title = "Prikaz osobe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (@Model.Osoba == null)
{
    <p>@Model.Odgovor.Text</p>
}
else
{
    <fieldset>
        <legend>@Model.Osoba.Ime @Model.Osoba.Prezime (ID:@Model.Osoba.Id)</legend>

        <div class="editor-label">
            Ime
        </div>
        <div class="editor-field">
            @Model.Osoba.Ime
        </div>

        <div class="editor-label">
            Prezime
        </div>
        <div class="editor-field">
            @Model.Osoba.Prezime
        </div>
            
        <div class="editor-label">
            Broj računa
        </div>
        <div class="editor-field">
            @Model.Osoba.Racuni.Count
        </div>
    </fieldset>
}

labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>ASP.NET MVC 3 REST</h1>
            </div>
            <div id="logindisplay">
                ...by mama
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Početna", "Index", "Osoba")</li>
                    <li>@Html.ActionLink("Dodaj osobu", "Dodaj", "Osoba")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

labosi/lab-1/2011-12/by_mama/MVCREST/MVCREST.Server/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}